config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources:productos
  get 'login/index', as: 'login'
  get 'productos/index'
  get 'productos/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
  
  root 'productos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def resource_name
        :user
      end
     
      def resource
        @resource ||= User.new
      end
    
      def resource_class
        User
      end
     
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/controllers/carrito_controller.rb
class CarritoController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  def _log
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
    def index
        @productos = Product.all
    end
    #GET /productos/:id
    def show
        @producto = Product.find(params[:id])
    end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrito_helper.rb
module CarritoHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/carrito/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light">

<h1>Mi carrito</h1>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    -->

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
  
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark pt-4 pb-4 tema">
        <div class="col-lg-1"></div>
        <a class="navbar-brand ml-5 pl-5" <%= link_to "Tienda Online", root_path %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
       
        <div class="ml-3 col-sm-10 col-lg-6 col-xl-12 col-md-12">
        <input type="text" class="form-control " placeholder="Buscar producto" id="buscador">
        </div>
        <li class="nav-item">
        <a class="navbar-brand ml-4"><i class="material-icons md-light">shopping_cart</i></a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons md-light">account_circle</i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" <%= link_to "Cierra sesion", destroy_user_session_path, method:"delete" %></a>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
        <a type="button" class="navbar-brand ml-2 mr-3" data-toggle="modal" data-target="#exampleModalLong"><i class="material-icons md-light">account_circle</i></a>
        </li>
        <% end %>

        
        </ul>
        </div>
      </nav>
      
    </header>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="d-flex justify-content-center" style="background-color: #f4f4f4;">
            <h4 class="titulo-login">Iniciar Sesion</h4>
          </div>
          <div class="modal-body">
            <%= form_for(:user, :url => session_path(:user)) do |f| %>
              <label class="mt-0">E-mail</label>
              <%= f.text_field :email, class:"form-control" %>
              <label class="mt-4">Contraseña</label>
              <%= f.password_field :password, class:"form-control" %>
              
              <div class="d-flex justify-content-between mt-3">
                <div>
                <%= f.check_box :remember_me %>
                <%= f.label :Recuerdame %>
                </div>
                <div>
                <%= link_to "¿Olvidó su contraseña?", new_password_path(:user) %>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <%= f.submit 'Iniciar sesion',class:"btn btn-outline-danger" %>
              <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Volver</button>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    

    <%= yield %>
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/login/_log.html.erb
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="d-flex justify-content-center" style="background-color: #f4f4f4;">
                <h4 class="titulo-login">Iniciar Sesion</h4>

            </div>
          <div class="modal-body">
        
                    <form>
                    
                        
                        <label class="mt-2">E-mail</label>
                            <input type="text" class="form-control" placeholder="usuario" style="background: #f2f2f2;border:none">
                        
                        
                        <label class="mt-4">Contraseña</label>
                            <input type="password" class="form-control" placeholder="contraseña" style="background: #f2f2f2;border:none">
                        
                    </form>
    
          </div>
          <div class="modal-footer">

            <button type="button" class="btn btn-outline-danger">Ingresar</button>
            <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Volver</button>
            
          </div>
        </div>
      
  </div>
</div>

app/views/login/index.html.erb
<div class="col-12 mt-3 mb-3">
    <div class="container bg-light">
        <div class="col-6">
            <div class="col-6">
                <h3>LOGIN</h3>
            </div>
            <form>
                <div class="col-4 mb-3">
                    <input type="text" class="form-control" placeholder="usuario">
                </div>
                <div class="col-4 mb-3">
                    <input type="password" class="form-control" placeholder="contraseña">
                </div>
                <div class="col-12 mb-3">
                    <button class="btn btn-dark">Ingresar</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/views/productos/index.html.erb
<div class="container mt-3">
    <div class="col-12 banner-tema">
        <h2 class="banner-titulo">Productos</h2>
    </div>
    <div class="row">
    <% @productos.each do |producto| %>
        <div class="card ml-3 mr-3" style="width: 17rem;">
            <div class="card-body">
                <%= link_to producto_path(producto.id) do %>
                <img class="card-img-top" <%= image_tag(producto.urlimagen) %> 
                <% end %>
                <h5 class="titulo-producto mt-4" style="text-align: center;"><%= producto.nombre %></h5>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <p class="precio-titulo" style="color: #737373;">Precio: </p>
                    <p class="precio-numero">S/.<%= producto.precio %></p>  
                </div>    
                <div class="row" >
                    <div class="col-sm-3 p-0">
                        <input class="form-control" style="height:100%;background-color: #f2f2f2;font-size: .875rem;text-align: center;border:0;font-weight: 600;" type="text" value="1">
                    </div>
                    <div class="column p-0">
                        <div class="col-sm-3">
                        <button type="button" class="btn btn-dark p-0 pl-2 pr-2" style="border:none;"><i class="material-icons md-light md-12">add</i></button>
                        </div>
                        <div class="col-sm-3 h-25">
                        <button type="button" class="btn btn-secondary p-0 pl-2 pr-2" style="border:none;"><i class="material-icons md-light md-12">remove</i></button>
                        </div>
                    </div>
                    <div class="row m-1">
                    </div>
                    <button type="button" class="btn text-light p-1 pl-4 pr-4" style="background-color:  #ec1c24;font-weight: 600;">AGREGAR</button>
                </div>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/productos/show.html.erb
<div class="container mt-5">
    <div class="d-flex justify-content-center">
        <div class="row">
            <div class="column">
                <%= image_tag(@producto.urlimagen) %> 
            </div>


            <div class="column">
                <div class="row">
                    <p class="nom-pro"><%= @producto.nombre  %></p>
                </div>
                <div class="row">
                    <p class="marca">GLORIA</p>
                    <p class="cod-pro">Codigo de producto: <%= @producto.id %></p>
                </div>
                <div class="row">
                <p class="caracteristicas-title">Características:</p>
                </div>
                <div class="row">
                <p class="caracteristicas"><%= @producto.descripcion  %></p>
                </div>
                <div class="row justify-content-between">
                    <p class="caracteristicas">Precio: </p>
                    <p class="precio">S/. <%= @producto.precio  %></p>
                </div>
                <div class="row" >
                    <div class="col-sm-3 p-0">
                        <input class="form-control" style="height:100%" type="text" value="1">
                    </div>
                    <div class="column p-0">
                        <div class="col-sm-3">
                        <button type="button" class="btn btn-dark p-0 pl-2 pr-2" style="border:none;"><i class="material-icons md-light md-12">add</i></button>
                        </div>
                        <div class="col-sm-3 h-25">
                        <button type="button" class="btn btn-secondary p-0 pl-2 pr-2" style="border:none;"><i class="material-icons md-light md-12">remove</i></button>
                        </div>
                    </div>
                    <div class="row m-1">
                         
                    </div>
                    <div class="row">
                        <button type="button" class="btn text-light p-1 pl-4 pr-4" style="background-color:  rgb(236, 28, 36);font-weight: 600;">AGREGAR AL CARRITO</button>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>